title: RecordType
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://jinyoo1021.github.io/blog

aux_links:
  Template Repository: https://github.com/jinyoo1021/blog
